//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hiedlogsws.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HIEDEntities : DbContext
    {
        public HIEDEntities()
            : base("name=HIEDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<request> request { get; set; }
        public virtual DbSet<response> response { get; set; }
        public virtual DbSet<socialMedia> socialMedia { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
