//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hiedlogsws.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class request
    {
        public string userId { get; set; }
        public string method { get; set; }
        public string ip { get; set; }
        public string device { get; set; }
        public string browser { get; set; }
    }
}
